// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibzwovbcwwbbfyomjwqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliendvdmJjd3diYmZ5b21qd3FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NjQ5ODcsImV4cCI6MjA2MzQ0MDk4N30.1jFv1hwuZ-PIntQs-TIZkc9uLNWcp7iNVN7Io-gGDRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);